### ISSUE TITLE
I see someone use route table but not iptable6 is it suitable for this?

### ISSUE THREAD

**Issue by youxiaojie** [burghardt/easy-wg-quick#43]
I see someone use route table but not iptable6 is it suitable for this? what is the difference by two method between iptable6 and ip route? in my view , iptable6 can using fd00:: address by nat, route is used when we can get a /64 public routable ipv6,is it right?

eg. I use HE broker get /64 routable address, can I using it in vpn?

**Comment by burghardt** [comment]
> what is the difference by two method between iptable6 and ip route?

First method use [NAT](https://en.wikipedia.org/wiki/Network_address_translation), second method use [NDP](https://en.wikipedia.org/wiki/Neighbor_Discovery_Protocol) proxy. NAT is easier to configure, but has [some limitations](https://en.wikipedia.org/wiki/Network_address_translation#Issues_and_limitations).

> eg. I use HE broker get /64 routable address, can I using it in vpn?

Yes, you can subdivide this network. [Enabling NDP proxy (instead of default IPv6 masquerading)](../blob/master/README.md#enabling-ndp-proxy-instead-of-default-ipv6-masquerading) part of [README.md](../blob/master/README.md) explain this in details.
