### ISSUE TITLE
Renaming wghub.conf --> wg0.conf

### ISSUE THREAD

**Issue by MrksHfmn** [burghardt/easy-wg-quick#8]
thanks for the script. it works as expected. please use the standard naming for the network device wg0 to make it conform to the wireguard standard. systemd also expects these names.

**Comment by burghardt** [comment]
I took a look at interface naming and according to `wg-quick` manual:

> Recommended  INTERFACE  names include `wg0` or `wgvpn0` or even `wgmgmtlan0`.  However, the number at the end is in fact optional, and really any free-form string [a-zA-Z0-9_=+.-]{1,15} will work. So even interface names corresponding  to  geographic  locations  would suffice, such as `cincinnati`, `nyc`, or `paris`, if that's somehow desirable.

This is probable not a big change, but does it bring any advantages?

**Comment by burghardt** [comment]
Looks like `systemd` doesn't care about the name at least for `wg-quick.service` (4b7b88e). I will keep this open for a while, but I don't see any advantages of this change. On the other hand having names like `wghub(.conf)` and `wgclientXY(.conf)` instead of series of `wg0(.conf)` makes obvious which is for what.

If name of interface is important, user can rename generated configuration file while installing it to `/etc/wireguard`:
```
sudo cp wghub.conf /etc/wireguard/wg0.conf
```
